export const TransContent : any = {
  en: {
    home: 'Home',
    pokemonType: 'Pokemon Type',
    mainTitle: 'All the Pokémon data you&apos;ll ever need in one place!',
    subTitle: 'Thousand of compiled data into one',
    ctaTitle: 'Check PokèDex',
    generation: 'All Generation Totaling',
    page: 'Page',
    weight: 'Weight',
    height: 'Height',
    abilities: 'Abilities',
    type: 'Type',
    oImages: 'Other Images',
    stats : 'Stats',
    evolution : 'Evolution',
    more: 'More Detail',
    pokemonWithType: 'Pokemon With Type',
    normal : 'normal',
    fighting : 'fighting',
    flying : 'flying',
    poison : 'poison',
    ground : 'ground',
    rock : 'rock',
    bug : 'bug',
    ghost : 'ghost',
    steel : 'steel',
    fire : 'fire',
    water : 'water',
    grass : 'grass',
    electric : 'electric',
    psychic : 'psychic',
    ice : 'ice',
    dragon : 'dragon',
    dark : 'dark',
    fairy : 'fairy',
    unknown : 'unknown',
    shadow : 'shadow'
  },
  id: {
    home: 'Beranda',
    pokemonType: 'Tipe Pokemon',
    mainTitle: 'Semua Data Pokemon yang Kamu Butuhkan Dalam Satu Tempat',
    subTitle: 'Ribuan data yang dikompilasi menjadi satu',
    ctaTitle: 'Periksa PokèDex',
    generation: 'Semua Generasi Berjumlah',
    page: 'Halaman',
    weight: 'Berat',
    height: 'Tinggi',
    abilities: 'Kemampuan',
    type: 'Tipe',
    oImages: 'Gambar Lainnya',
    stats : 'Status',
    evolution : 'Evolusi',
    more: 'Lihat Detail',
    pokemonWithType: 'Pokemon Dengan Tipe',
    normal : 'Normal',
    fighting : 'Berkelahi',
    flying : 'Terbang',
    poison : 'Racun',
    ground : 'Tanah',
    rock : 'Batu',
    bug : 'Serangga',
    ghost : 'Hantu',
    steel : 'Baja',
    fire : 'Api',
    water : 'Air',
    grass : 'Rumput',
    electric : 'Listrik',
    psychic : 'Cenayang',
    ice : 'Es',
    dragon : 'Naga',
    dark : 'Kegelapan',
    fairy : 'Peri',
    unknown : 'Tidak Diketahui',
    shadow : 'Bayangan'
  }
};